<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>House Of Bhavana | Email Verification</title>

</head>
<body style="text-align: center; margin: 20px auto;  padding-left: 10%; padding-right: 10%; padding-top: 20px; font-family: Nunito Sans, sans-serif; background-color: #e2e2e2; display: block; position: relative;">
<table cellpadding="0" cellspacing="0" style="background-color: #fff; width: 100%; border-collapse: collapse; border-spacing: 0;">
    <tbody>
        <tr>
            <td>
                <table cellpadding="0" cellspacing="0" width="100%">
                    <tr class="header">
                        <td valign="top" style="padding-top: 20px;">
                            <img clicktracking="off" src="{{asset('assets/fixed-image/logo.png')}}"  style="width: 30px;
                            height: auto;" alt="logo" />
                            <h3 style="font-family: Trebuchet MS, Tahoma, sans-serif;">
                                BHAVANA
                            </h3>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>

        <tr>
            <td class="banner" style="position: relative;">
                <table>
                    <tr>
                        <td colspan="2">
                            <img clicktracking="off" style="width: 100%; margin-bottom: -6px;" src="{{ asset('assets/images/banner5.jpg') }}" alt="banner" />
                        </td>
                    </tr>
                </table>
            </td>
        </tr>

        <tr>
            <td style="margin-top: 30px; display: block;">
                <table style="width: 100%">
                    <tr>
                        <td>
                            <h1 style="margin-bottom: 6px; font-weight: bold; font-size: 16px; line-height: 20px; color: #252525;">Hi {{ $name }} And Welcome To House Of Bhavana.!</h1>
                            <p style="font-weight: 600; font-size: 14px; line-height: 20px; text-align: center; color: #939393; margin-bottom: -4px;">
                                We hope our product will lead you, like many other before you. to a place where your-ideas where your ideas can spark and grow.n a place where you’ll find all your inspiration
                                needs. before we get started, we’ll need to verify your email.
                            </p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>

        <tr>
            <td>
                <a clicktracking="off" href="{{ route('home').'/'.'verification'.'?id='.$userId.'&verification='.$link }}" style="text-decoration: none; font-weight: bold; font-size: 1rem; line-height: 18px; display: inline-block; color: #ffffff; background: #ff4c3b; border-radius: 6px; padding: 15px; margin-top: 25px;">Verify Email</a>
            </td>
        </tr>

        <tr>
            <td style="padding: 30px">
                <p style="font-weight: 600; font-size: 14px; line-height: 20px; text-align: center; color: #939393; margin-bottom: -4px;">
                    If you have any question, please email us at <a href="javascript:void(0)" style="text-decoration: none; font-weight: bold; text-decoration-line: underline; color: #ff4c3b;">care@houseofbhavana.in </a> or visit our <a href="javascript:void(0)" style="text-decoration: none;"> FAQs.</a> You can also chat with a real
                    live human during our operating hours. they can answer questions about account or help you with your meditation practice.
                </p>
            </td>
        </tr>

        <tr>
            <td colspan="2" class="section-t" style="background-color: #212121; padding: 26px">
                <table style="position: relative;
                width: 100%;">
                    <tr>
                        <td>
                    <tr>
                        <td>
                            <p style="font-weight: 800; font-size: 12px; line-height: 23px; text-align: center; letter-spacing: 1px; color: #e4e4e4; margin-top: 15px; text-transform: uppercase;">THIS EMAIL WAS AUTOGENERATED BY SYSTEM. MADE WITH BY DESIGN HOB TEAM.</p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
</body>
</html>
